# fly.toml app configuration file generated for assomdevgit on 2023-10-23T22:24:27+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "assomdevgit"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
